config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  root 'homes#top'
  get "/guest" => 'homes#guest'

  get "/my_page" => 'users#show'
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  resources :informations, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :comments, only:[:create, :destroy] do
      resource :reports, only:[:create, :destroy]
    end
  end
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :registrations => 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :password, presence: true, on: :create
  validates :name, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :informations
  has_many :favorites, dependent: :destroy
  has_many :current_locations, dependent: :destroy


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]


  protected



  def reject_user
    @user = User.find_by(email: params[:user][:email])
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == true)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_path
      else
        flash[:notice] = "入力が正しくありません"
      end
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user=User.find(current_user.id)
  end

  def withdrawal
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  def edit
    @user=User.find(current_user.id)
  end

  def updated
    @user=User.find(current_user.id)
    @user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container-lg px-5 px-sm-0">
  <h2 class="m-3">マイページ</h2>
  <% if flash[:notice] %>
    <p id="notice" class="text-success">
      <%= flash[:notice] %>
    </p>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-md-7 col-lg-7 px-1 px-sm-0 mx-auto text-left">
      <div id='map'></div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4 px-1 px-sm-0 mx-0 border rounded-dark">
      <div>
        <div class="text-center">
          <h3 class="m-2">ユーザー情報</h3>
        </div>
        <div>
          <h5 class="m-3">・ユーザーネーム</h5>
          <p class="m-3"><%= @user.name %></p>
        </div>
        <div>
          <h5 class="m-3">・メールアドレス</h5>
          <p class="m-3"><%= @user.email %></p>
        </div>
        <div class="m-3 text-right">
          <%= link_to edit_user_registration_path(current_user.id) do %>
            <p class="btn btn-info">編集する</p>
          <% end %>
        </div>
        <div class="text-center">
          <h3>マーカー表示切替</h3>
          <div class="m-4">
            <div>
              <button type="button" id="information_button" class="m-1 btn btn-primary btn-block">
                自分の投稿
              </button>
            </div>
            <div>
              <button type="button" id="favorite_botton" class="m-1 btn btn-secondary btn-block">
                ブックマークした投稿
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 m-3 text-center">
      <%= link_to "戻る", :back, class: "btn btn-outline-info", data: { 'turbolinks': false } %>
    </div>
  </div>
</div>

  <style>
    #map {
        height: 500px;
        width: 100%;
    }
  </style>

  <script>
      let map, marker1 = [],marker2 = []


      function initMap() {
        geocoder = new google.maps.Geocoder()

        const information_count=<%= @user.informations.count %>

        const favorite_count=<%= @user.favorites.count %>

        map = new google.maps.Map(document.getElementById('map'), {
            center: {
              lat: 35.001637,
              lng: 135.767667
            },
              zoom: 1,
        });

        <% @user.informations.each do |information| %>
          $('#information_button').click(function(){
            const contentString = "<%= information.title %>";

            marker1.push(new google.maps.Marker({
                position:{lat: <%= information.latitude %>, lng: <%= information.longitude %>},
                map: map,
                title: contentString
            }));
            
            google.maps.event.addListener(marker1[marker1.length - 1], 'click', (function(url){
              return function(){ location.href = url; };
            })("<%= information_path(information.id) %>"));

            for (let i = 0; i < marker2.length; i++) {
              marker2[i].setMap(null);
            }
            marker2 = [];
          });

        <% end %>

        <% @user.favorites.each do |favorite| %>
          $('#favorite_botton').click(function(){
            const contentString = "<%= favorite.information.title %>";

            marker2.push(new google.maps.Marker({
                position:{lat: <%= favorite.information.latitude %>, lng: <%= favorite.information.longitude %>},
                map: map,
                title: contentString
            }));
            google.maps.event.addListener(marker2[marker2.length - 1], 'click', (function(url){
              return function(){ location.href = url; };
            })("<%= information_path(favorite.information.id) %>"));

            for (let i = 0; i < marker1.length; i++) {
              marker1[i].setMap(null);
            }
            marker1 = [];
          });
        <% end %>
      }

  </script>

  <script
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap"
    async defer>
  </script>

app/views/users/unsubscribe.html.erb
<div class="text-center m-5">
  <h1 class="m-5">退会手続き</h1>
  <p class="m-5">
    退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>
    再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>
    本当に退会してよろしいですか？
  </p>
  <div class=m-4>
    <div class="m-2">
      <%= link_to  withdrawal_path, method: :patch,  data: { confirm: "【最終確認】退会しますか？" } do %>
        <p class="btn btn-outline-danger">退会する</p>
      <% end %>
    </div>
    <div class="m-2">
      <%= link_to  my_page_path(current_user) do %>
        <p class="btn btn-outline-primary">退会しない</p>
      <% end %>
    </div>
  </div>
</div>