config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  root 'homes#top'
  get "/guest" => 'homes#guest'

  get "/my_page" => 'users#show'
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  resources :informations, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :comments, only:[:create, :destroy] do
      resource :reports, only:[:create, :destroy]
    end
  end
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :registrations => 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :information
  belongs_to :user

  has_many :reports, dependent: :destroy

  validates :body, presence: true

  def reported_by?(user)
    reports.exists?(user_id: user.id)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :information
  
end

app/models/information.rb
class Information < ApplicationRecord

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3}
  validates :body, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/report.rb
class Report < ApplicationRecord

  belongs_to :user
  belongs_to :comment

  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :password, presence: true, on: :create
  validates :name, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :informations
  has_many :favorites, dependent: :destroy
  has_many :current_locations, dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_account_update_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

  def configure_account_update_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_pathfor(resource)
    root_path
  end

  protected


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    information = Information.find(params[:information_id])
    comment = current_user.comments.new(comment_params)
    comment.information_id = information.id
    comment.save
    redirect_to information_path(information)
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to information_path(params[:information_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :information_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    information = Information.find(params[:information_id])
    favorite = current_user.favorites.new(information_id: information.id)
    favorite.save
    redirect_to information_path(information)
  end

  def destroy
    information = Information.find(params[:information_id])
    favorite = current_user.favorites.find_by(information_id: information.id)
    favorite.destroy
    redirect_to information_path(information)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end

  def guest
    @maps=Information.all
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action :authenticate_user!
  before_action :information_user, only:[:edit, :update, :destroy]

  def new
    @map=Information.new
  end

  def create
    @map=Information.new(info_params)
    @map.user_id=current_user.id
    if @map.save
      flash[:notice] ="投稿しました"
      redirect_to information_path(@map.id)
    else
      render :new
    end
  end

  def index
    @maps=Information.all
  end

  def show
    @map=Information.find(params[:id])
    @comment=Comment.new
    @comments=@map.comments.order(created_at: :desc)
  end

  def edit
    @map=Information.find(params[:id])
  end

  def destroy
    @map=Information.find(params[:id])
    @map.user_id=current_user.id
    @map.delete
    flash[:notice] ="削除しました"
    redirect_to my_page_path
  end

  def update
    @map=Information.find(params[:id])
    @map.user_id=current_user.id
    if @map.update(info_params)
      redirect_to information_path(@map.id)
      flash[:notice] ="上書きしました"
    else
      render :edit
    end
  end

  private

  def information_user
    @info = Information.find(params[:id])
    unless @info.user == current_user
      redirect_to my_page_path
    end
  end

  def info_params
    params.require(:information).permit(:title, :body, :latitude, :longitude, :address)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
before_action :authenticate_user!

  def create
    information = Information.find(params[:information_id])
    report = Report.new(user_id: current_user.id, comment_id: report_params)
    report.save
    redirect_to information_path(information)
  end

  def destroy
    information = Information.find(params[:information_id])
    report = Report.find_by(comment_id: report_params)
    report.destroy
    redirect_to information_path(information)
  end

  def report_params
    params.require(:comment_id)
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user=User.find(current_user.id)
  end

  def withdrawal
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  def edit
    @user=User.find(current_user.id)
  end

  def updated
    @user=User.find(current_user.id)
    @user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countrys_helper.rb
module CountrysHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/informations/_form_map.html.erb
<script>
  let map
    
  function initMap() {
    const geocoder = new google.maps.Geocoder()
  
    map = new google.maps.Map(document.getElementById('map'), {
      center: {
        lat: 38.001637,
        lng: 135.767667
      },
      zoom: 5,
    });
    map.addListener( 'click', function(event) {
      placeMarker(event.latLng);
    });
    let marker
    function placeMarker(location) {
  
      if ( marker ) {
        marker.setPosition(location);
      } else {
        marker = new google.maps.Marker({
          position: location,
          map: map,
          draggable: true,
        });
      };
      document.getElementById('lat').value = location.lat();
      document.getElementById('lng').value = location.lng();
      map.panTo(location);
    };
  };
  
  var getMap = (function() {
    function codeAddress(address) {
  
      var geocoder = new google.maps.Geocoder();
  
      geocoder.geocode( { 'address': address}, function(results, status) {
  
        if (status == google.maps.GeocoderStatus.OK) {
  
          map.setCenter(results[0].geometry.location);
  
          document.getElementById('lat').value=results[0].geometry.location.lat();
          document.getElementById('lng').value=results[0].geometry.location.lng();
  
  
        } else {
            console.log('Geocode was not successful for the following reason: ' + status);
        }
  
      });
  
    }
  
  
    return {
      getAddress: function() {
        var button = document.getElementById("map_button");
  
        button.onclick = function() {
  
          var address = document.getElementById("address").value;
  
          codeAddress(address);
        }
  
        window.onload = function(){
  
         var address = document.getElementById("address").value;
         codeAddress(address);
        }
      }
  
    };
  
  })();
  getMap.getAddress();
</script>

<script
  src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap"
  async defer>
</script>

app/views/informations/_map.html.erb
<script>
  let map

  function initMap() {

    map = new google.maps.Map(document.getElementById('map'), {
      center: {
        lat: 35.001637,
        lng: 135.767667
      },
       zoom: 3,
    });

    <% maps.each do |map| %>
      (function(){
        var contentString = "<%= map.title %>";

        var marker = new google.maps.Marker({
          position:{lat: <%= map.latitude %>, lng: <%= map.longitude %>},
          map: map,
          title: contentString,
        });

        google.maps.event.addListener(marker, 'click', (function(url){
          return function(){ location.href = url; };
        })("<%= information_path(map.id) %>"));

      })();
    <% end %>

     $('#location_button').click(function() {
      navigator.geolocation.getCurrentPosition(function (position) {
        var LatLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

        map = new google.maps.Map(document.getElementById('map'), {
            center: LatLng,
            zoom: 15,
        })

        <% maps.each do |map| %>

            var contentString = "<%= map.title %>";

            var marker = new google.maps.Marker({
                position:{lat: <%= map.latitude %>, lng: <%= map.longitude %>},
                map: map,
                title: contentString
            });

            google.maps.event.addListener(marker, 'click', (function(url){
              return function(){ location.href = url; };
            })("<%= information_path(map.id) %>"));

        <% end %>
      });
    });
  }

  var getMap = (function() {
    function codeAddress(address) {

      var geocoder = new google.maps.Geocoder();

      geocoder.geocode( { 'address': address}, function(results, status) {

        if (status == google.maps.GeocoderStatus.OK) {

          map.setCenter(results[0].geometry.location);

          document.getElementById('lat').value=results[0].geometry.location.lat();
          document.getElementById('lng').value=results[0].geometry.location.lng();

        };
      });
    };


    return {
      getAddress: function() {
        var button = document.getElementById("map_button");

        button.onclick = function() {

          var address = document.getElementById("address").value;

          codeAddress(address);
        }

        window.onload = function(){

          var address = document.getElementById("address").value;
          codeAddress(address);
        };
      }
    };

  })();
  getMap.getAddress();
</script>




<script
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap"
    async defer>
</script>

app/views/informations/edit.html.erb
<div class="container-lg px-5 px-sm-0">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 px-5 px-sm-0 m-4">
      <form onsubmit="return false;">
        <h3>マップ検索</h3>
        <% if @map.errors.any? %>
          <%= @map.errors.count %>件のエラーが発生しました
          <ul>
            <% @map.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <input type="text" placeholder="国名、地名" id="address">
        <button type="button" value="検索" id="map_button">検索</button>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-6 px-1 px-sm-0 m-2" >
      <div id='map'></div>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-5 px-1 px-sm-0 m-2 border rounded-derk">
      <div>
        <%= form_with model: @map, url: information_path, data: { confirm: "【確認】内容を変更しますか?" } do |f| %>
          <%= f.hidden_field :latitude, id: 'lat' %>
          <%= f.hidden_field :longitude, id: 'lng' %>
          <div>
            <h3>タイトル</h3>
            <div class="m-2">
              <%= f.text_field :title, style: "width:100%" %>
            </div>
          </div>
            <h3>内容</h3>
          <div class="m-2">
            <%= f.text_area :body, style: "width:100%; height:325px" %>
          </div>
          <div class="text-right">
            <%= f.submit "編集する",class:"btn btn-outline-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 mt-lg-4 text-center">
      <%= link_to informations_path,  data: { 'turbolinks': false } do %>
        <p class="btn btn-outline-info">
          投稿一覧
        </p>
      <% end %>
    </div>
  </div>
</div>

<style>
  #map {
    height: 500px;
    width: 100%;
  }
</style>

<%= render 'form_map' %>

app/views/informations/index.html.erb
<div class="container-lg px-5 px-sm-0">
  <h2 class="m-3">投稿一覧</h2>
  <div class="row">
    <div class="col-sm-11 col-md-5 col-lg-5 px-5 px-sm-0 m-4">
      <form onsubmit="return false;">
        <h3>マップ検索</h3>
        <div class="input-group">
          <input class="form-control" type="text" placeholder="国名、地名" id="address">
          <button type="button" value="検索" id="map_button" class="btn btn-outline-info">検索</button>
        </div>
      </form>
      <button type="button" value="検索" id="location_button" class="btn btn-secondary">現在地周辺から検索</button>
    </div>
    <div class="col-sm-11 col-md-5 col-lg-5 px-5 px-sm-0 m-4 text-center">
      <div>
        <i>
          ～～楽しい旅行を犯罪被害で台無しにしないために～～<br><br>
          旅行を予定している国、地域周辺の投稿で下調べしよう！<br>
          観光地でも油断は禁物です！！
        </i>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 px- px-sm-0 mx-2">
      <div id='map'></div>
    </div>
  </div>
</div>


<style>
    #map {
        height: 600px;
        width: 100%;
    }
</style>

<%= render 'map', maps: @maps %>

app/views/informations/new.html.erb
<div class="container-lg px-5 px-sm-0">
  <h2 class="m-3">新規投稿</h2>
  <div class="row">
    <div class="col-sm-11 col-md-5 col-lg-5 px-5 px-sm-0 m-4">
      <form onsubmit="return false;">
        <h3>マップ検索</h3>
        <% if @map.errors.any? %>
          <%= @map.errors.count %>件のエラーが発生しました
          <ul>
            <% @map.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <div class="input-group">
          <input class="form-control" type="text" placeholder="国名、地名" id="address">
          <button type="button" value="検索" id="map_button" class="btn btn-outline-info">検索</button>
        </div>
      </form>
    </div>
    <div class="col-sm-11 col-md-5 col-lg-5 px-5 px-sm-0 m-4 text-center">
      <div>
        <i>
          あなたが体験した旅先での被害を投稿してみよう<br>
          この投稿が誰かの参考になるかもしれません!
        </i>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-6 px-1 px-sm-0 m-2" >
      <div id='map'></div>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-5 px-1 px-sm-0 m-2 border rounded-derk">
      <div>
        <%= form_with model: @map, url: informations_path, data: { confirm: "【確認】内容を投稿しますか?" } do |f| %>
          <%= f.hidden_field :latitude, id: 'lat' %>
          <%= f.hidden_field :longitude, id: 'lng' %>
          <div>
            <h3 class=mt-2>タイトル</h3>
            <div class="m-2">
              <%= f.text_field :title, style: "width:100%",
              placeholder: "例：○○通りでスリに遭いました"%>
            </div>
          </div>
            <h3>詳細</h3>
          <div class="m-2">
            <%= f.text_area :body, style: "width:100%; height:320px",
            placeholder: "例：　観光名所でスリ被害に遭いました...
            海外ではスリや置き引きが絶えません。
            リュックは前にかけ貴重品の管理に注意しましょう！" %>
          </div>
          <div class="text-right"><%= f.submit "投稿する",class:"btn btn-outline-primary" %></div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 mt-lg-4 text-center">
      <%= link_to informations_path,  data: { 'turbolinks': false } do %>
        <p class="btn btn-outline-info">
          投稿一覧
        </p>
      <% end %>
      <%= link_to  :back  do %>
        <p class="btn btn-outline-info">
          戻る
        </p>
      <% end %>
    </div>
  </div>
</div>

<style>
  #map {
    height: 500px;
    width: 100%;
  }
</style>

<%= render 'form_map' %>

app/views/informations/show.html.erb
<div class=" container-lg px-5 px-sm-0">
  <% if flash[:notice] %>
    <p id="notice" class="text-success">
      <%= flash[:notice] %>
    </p>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-6 px-1 px-sm-0 mt-2">
      <div id='map'></div>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-5 px-1 px-sm-0 mx-0 mt-2 border rounded-dark">
      <div>
        <div class="m-1">
          <h3>タイトル</h3>
          <p class="m-3"><strong><%= @map.title %></strong></p>
        </div>
        <div class="m-1">
          <h3>内容</h3>
          <p class="m-3"><%= safe_join(@map.body.split("\n"),tag(:br)) %></p>
        </div>
      </div>
    </div>
    <div class="mt-1">
      投稿された日：<%=l @map.created_at, format: :short %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-10 px-5 px-sm-0 mx-auto mt-3">
      <div class="text-right">
        <% if @map.user_id==current_user.id %>
          <%= @map.favorites.count %> 名にブックマークされました
        <% else %>
          <% if @map.favorited_by?(current_user) %>
            <p class="btn btn-outline-danger">
              <%= link_to information_favorites_path(@map), method: :delete do %>
                <i class="fas fa-bookmark"></i><%= @map.favorites.count %> ブックマーク削除
              <% end %>
            </p>
          <% else %>
            <p class="btn btn-outline-primary" disabled>
              <%= link_to information_favorites_path(@map), method: :post do %>
                <i class="far fa-bookmark"></i><%= @map.favorites.count %> ブックマーク
              <% end %>
            </p>
          <% end %>
        <% end %>
        <% if @map.user_id==current_user.id %>
          <%= link_to edit_information_path(@map.id), data: { 'turbolinks': false } do %>
            <p class="btn btn-outline-primary">投稿を編集する</p>
          <% end %>
          <%= link_to information_path(@map.id), method: :delete, data: { confirm: "【確認】この投稿を削除しますか？" } do %>
          　<p class="btn btn-outline-warning">投稿を削除する</p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-12 col-lg-10 px-5 px-sm-0 mx-auto">
      <div>
        <table class="table">
          <div class="text-right">
            <%= form_with model: [@map, @comment] do |f| %>
              <%= f.text_field :body, size:"30" %>
              <%= f.submit "コメントする"%>
            <% end %>
          </div>
          <thead>
            <tr>
              <th>ユーザー</th>
              <th>コメント一覧</th>
              <th colspan="2"></th>
            </tr>
          </thead>
          <tbody>
            <% @comments.each do |comment| %>
              <tr>
                <td><%= comment.user.name %></td>
                <td><%= comment.body %></td>
                <td class="text-right">
                  <%=l comment.created_at, format: :short %>
                  <% if comment.user==current_user %>
                    <%= link_to information_comment_path(comment.information, comment), method: :delete do %>
                      <p　class="m-2 btn btn-info">削除</p>
                    <% end %>
                  <% else %>
                    <% if comment.reported_by?(current_user) %>
                      <p class="small btn btn-outline-danger">
                      <%= link_to information_comment_reports_path(@map.id, comment), method: :delete do %>
                        通報を取り消す
                      <% end %>
                      </p>
                    <% else %>
                      <p class="small btn btn-outline-danger" disabled>
                        <%= link_to information_comment_reports_path(@map.id, comment), method: :post, data: { confirm: "【確認】このコメントを通報しますか？" } do %>
                          通報
                        <% end %>
                      </p>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<style>
    #map {
        height: 500px;
        width: 100%;
    }
</style>

<script>
    let map

    const display = document.getElementById('display')

    function initMap() {
        geocoder = new google.maps.Geocoder()

        map = new google.maps.Map(document.getElementById('map'), {
            center: {
                lat: <%= @map.latitude %>,
                lng: <%= @map.longitude %>
            },
            zoom: 15,
        });

        (function(){
            var contentString = "<%= @map.title %>";

            var marker = new google.maps.Marker({
                position:{lat: <%= @map.latitude %>, lng: <%= @map.longitude %>},
                map: map,
                title: contentString
            });

        })();
    };

</script>

<script
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap"
    async defer>
</script>