config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  root 'homes#top'
  get "/guest" => 'homes#guest'

  get "/my_page" => 'users#show'
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  resources :informations, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :comments, only:[:create, :destroy] do
      resource :reports, only:[:create, :destroy]
    end
  end
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :registrations => 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :information
  belongs_to :user

  has_many :reports, dependent: :destroy

  validates :body, presence: true

  def reported_by?(user)
    reports.exists?(user_id: user.id)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :information
  
end

app/models/information.rb
class Information < ApplicationRecord

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3}
  validates :body, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/report.rb
class Report < ApplicationRecord

  belongs_to :user
  belongs_to :comment

  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :password, presence: true, on: :create
  validates :name, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :informations
  has_many :favorites, dependent: :destroy
  has_many :current_locations, dependent: :destroy


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    information = Information.find(params[:information_id])
    comment = current_user.comments.new(comment_params)
    comment.information_id = information.id
    comment.save
    redirect_to information_path(information)
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to information_path(params[:information_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :information_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    information = Information.find(params[:information_id])
    favorite = current_user.favorites.new(information_id: information.id)
    favorite.save
    redirect_to information_path(information)
  end

  def destroy
    information = Information.find(params[:information_id])
    favorite = current_user.favorites.find_by(information_id: information.id)
    favorite.destroy
    redirect_to information_path(information)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end

  def guest
    @maps=Information.all
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
before_action :authenticate_user!

  def create
    information = Information.find(params[:information_id])
    report = Report.new(user_id: current_user.id, comment_id: report_params)
    report.save
    redirect_to information_path(information)
  end

  def destroy
    information = Information.find(params[:information_id])
    report = Report.find_by(comment_id: report_params)
    report.destroy
    redirect_to information_path(information)
  end

  def report_params
    params.require(:comment_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user=User.find(current_user.id)
  end

  def withdrawal
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  def edit
    @user=User.find(current_user.id)
  end

  def updated
    @user=User.find(current_user.id)
    @user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countrys_helper.rb
module CountrysHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>TripscaryPlace</title>
    <meta content="width=device-width,initial-scale=1" name="viewport"/>
    <link href="https://fonts.googleapis.com/css?family=Ravi+Prakash" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-lg">
          <%= link_to  root_path, class:"navbar-brand" do %>
           <p class="p-1 border rounded bg-warning text-dark">
             <i class="fab fa-forumbee"></i>
             Tripscary_Place
             </p>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>

                 <li>
                  <%= link_to new_information_path, class:"nav-link text-light", data: { 'turbolinks': false } do %>
                  <span class="fa-w-20">
                  <i class="fas fa-plus-circle"></i>
                  新規投稿
                  </span>
                  <% end %>
                </li>

                <li>
                  <%= link_to my_page_path(current_user), class:"nav-link text-light",data: { 'turbolinks': false } do %>
                  <span class="fa-w-18">
                  <i class="fas fa-address-book"></i>
                  マイページ
                  </span>
                  <% end %>
                </li>

                <li>
                  <%= link_to informations_path, class:"nav-link text-light", data: { 'turbolinks': false } do %>
                  <span class="fa-w-18">
                  <i class="fas fa-map-marker-alt"></i>
                  投稿一覧
                  </span>
                  <% end %>
                </li>

                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                  <span class="fa-w-16">
                  <i class="fas fa-sign-out-alt"></i>
                  ログアウト
                  </span>
                  <% end %>
                </li>

              <% else %>

                <li>
                  <%= link_to root_path, class:"nav-link text-light" do %>
                  <span class="fa-w-18">
                  <i class="fas fa-home"></i>
                  TOP
                  </span>
                  <% end %>
                </li>

                <li>
                  <%= link_to guest_path, class:"nav-link text-light", data: { 'turbolinks': false } do %>
                  <span class="fa-w-16">
                  <i class="fas fa-map-marker-alt"></i>
                  投稿一覧
                  </span>
                  <% end %>
                </li>

                <li>
                  <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                  <span class="fa-w-16">
                  <i class="fas fa-user-plus"></i>
                  新規登録
                  </span>
                  <% end %>
                </li>

                <li>
                  <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                  <span class="fa-w-20">
                  <i class="fas fa-sign-in-alt"></i>
                  ログイン
                  </span>
                  <% end %>
                </li>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>